//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServempMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.legajos = new HashSet<legajos>();
        }
    
        public string Codigo { get; set; }
        public string ApellidoyNombre { get; set; }
        public string DomicilioParticular { get; set; }
        public string EntrecallesParticular { get; set; }
        public string BarrioParticular { get; set; }
        public string CPParticular { get; set; }
        public string LocalidadParticular { get; set; }
        public string TelefonoParticular { get; set; }
        public string NombreEmpresa { get; set; }
        public string DomicilioEmpresa { get; set; }
        public string EntrecallesEmpresa { get; set; }
        public string BarrioEmpresa { get; set; }
        public string CPEmpresa { get; set; }
        public string LocalidadEmpresa { get; set; }
        public string TelefonoEmpresa { get; set; }
        public string TipoCliente { get; set; }
        public Nullable<bool> HabDomPart1 { get; set; }
        public string DomicilioPart1 { get; set; }
        public string CPPart1 { get; set; }
        public string LocalidadPart1 { get; set; }
        public Nullable<bool> HabDomPart2 { get; set; }
        public string DomicilioPart2 { get; set; }
        public string CPPart2 { get; set; }
        public string LocalidadPart2 { get; set; }
        public Nullable<bool> HabDomPart3 { get; set; }
        public string DomicilioPart3 { get; set; }
        public string CPPart3 { get; set; }
        public string LocalidadPart3 { get; set; }
        public Nullable<bool> HabDomLab1 { get; set; }
        public string DomicilioLab1 { get; set; }
        public string CPLab1 { get; set; }
        public string LocalidadLab1 { get; set; }
        public Nullable<bool> HabDomLab2 { get; set; }
        public string DomicilioLab2 { get; set; }
        public string CPLab2 { get; set; }
        public string LocalidadLab2 { get; set; }
        public Nullable<System.DateTime> ProximaGestion { get; set; }
        public string CUIL { get; set; }
        public string Referencias { get; set; }
        public Nullable<decimal> Adulterado { get; set; }
    
        public virtual ICollection<legajos> legajos { get; set; }
    }
}
