//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServempMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class creditosEntities : DbContext
    {
        public creditosEntities()
            : base("name=creditosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<calificaciones> calificaciones { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<lotes> lotes { get; set; }
        public DbSet<legajos> legajos { get; set; }
    }
}
