//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServempMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class legajos
    {
        public int CodigoEmpresa { get; set; }
        public int NumeroEmpresa { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<System.DateTime> FechaCaida { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Cuenta { get; set; }
        public Nullable<decimal> NroLote { get; set; }
        public string Observaciones { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
