//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServempMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class lotes
    {
        public decimal NumeroLote { get; set; }
        public Nullable<decimal> CodFinanciera { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<decimal> TotalImporte { get; set; }
    }
}
